_BASE_: Base-DeepLabV3-OS16-Semantic.yaml
MODEL:
  WEIGHTS: "//home/kiran/kiran/Thesis/OOD/code/meta-ood/weights/deeplab_model_final_a8a355.pkl"
  PIXEL_MEAN: [0, 0, 0]
  PIXEL_STD: [1, 1, 1]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    DEPTH: 101
    NORM: "SyncBN"
    OUT_FEATURES: ["res2", "res5"]
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  SEM_SEG_HEAD:
    NAME: "DeepLabV3PlusHead"
    IN_FEATURES: ["res2", "res5"]
    PROJECT_FEATURES: ["res2"]
    PROJECT_CHANNELS: [48]
    NORM: "SyncBN"
    COMMON_STRIDE: 4
INPUT:
  FORMAT: "RGB"