_BASE_: Base-PanopticDeepLab-OS16.yaml
MODEL:
  #WEIGHTS: "x65.pkl"
  WEIGHTS: "./experiment_results/xception_sigmoid_bce_512_1024_bs16/model_0069999.pth"
  PIXEL_MEAN: [128, 128, 128]
  PIXEL_STD: [128, 128, 128]
  BACKBONE:
    NAME: "d2_xception_65"
  RESNETS:
    NORM: "SyncBN"
    RES4_DILATION: 1
    RES5_DILATION: 2
  PANOPTIC_DEEPLAB:
    USE_DEPTHWISE_SEPARABLE_CONV: True
  SEM_SEG_HEAD:
    USE_DEPTHWISE_SEPARABLE_CONV: True
SOLVER:
  MAX_ITER: 3720
  CHECKPOINT_PERIOD: 372
  BASE_LR: 0.0001
  IMS_PER_BATCH: 8
INPUT:
  FORMAT: "RGB"
  CROP:
    SIZE: (1024,2048)

OUTPUT_DIR: "./experiment_results/xception_sigmoid_bce_512_1024_bs16_69999_with_cityscapes_ood_no_freezing"
