_BASE_: Base-PanopticDeepLab-OS16.yaml
MODEL:
  WEIGHTS: "x65.pkl"
  PIXEL_MEAN: [128, 128, 128]
  PIXEL_STD: [128, 128, 128]
  BACKBONE:
    NAME: "d2_xception_65"
  RESNETS:
    NORM: "SyncBN"
    RES4_DILATION: 1
    RES5_DILATION: 2
  PANOPTIC_DEEPLAB:
    USE_DEPTHWISE_SEPARABLE_CONV: True
  SEM_SEG_HEAD:
    USE_DEPTHWISE_SEPARABLE_CONV: True
SOLVER:
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
  BASE_LR: 0.0005
INPUT:
  FORMAT: "RGB"
  CROP:
    SIZE: (1024,2048)

OUTPUT_DIR: "./experiment_results/xception_sigmoid_bce_1024_2048_bs16_no_void"
